### ISSUE TITLE
Enforce Conventional Commits being used when contributing to the repository

### ISSUE THREAD

**Issue by matthew-spire** [matthew-spire/dota-info#4]
https://www.conventionalcommits.org/en/v1.0.0/

## Acceptance Criteria

- [ ] When contributing to the project, a pre-commit hook should automatically run and ensure that the commit history matches the conventional commit spec

## Implementation Plan
- [ ] Integrate Gradle plugin for defining Conventional Commit types
- [ ] Define any custom types that are desired for the project
